version: '3.8'

services:
  wirebarley-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wirebarley-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:wirebarley;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
      - SERVER_PORT=8080
      - TZ=Asia/Seoul
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - wirebarley-network
    labels:
      - "com.wirebarley.service=main"
      - "com.wirebarley.description=Wirebarley Banking Service"

networks:
  wirebarley-network:
    driver: bridge
    name: wirebarley-network
