version: '3.8'

services:
  # H2 데이터베이스 웹 콘솔을 위한 별도 서비스 (개발용)
  h2-console:
    image: oscarfonts/h2:2.2.220
    container_name: wirebarley-h2-console
    ports:
      - "8081:81"
      - "9092:1521"
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - wirebarley-network
    volumes:
      - h2-data:/opt/h2-data

  wirebarley-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=development
    container_name: wirebarley-service-dev
    ports:
      - "8080:8080"
      - "5005:5005"  # 디버그 포트
    environment:
      - SPRING_PROFILES_ACTIVE=dev,docker
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-console:1521/wirebarley
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - LOGGING_LEVEL_COM_YL_WIREBARLEY=DEBUG
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - TZ=Asia/Seoul
    depends_on:
      - h2-console
    networks:
      - wirebarley-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  h2-data:
    driver: local

networks:
  wirebarley-network:
    driver: bridge
    name: wirebarley-network-dev
