spring:
  application:
    name: wirebarley-service
  datasource:
    url: jdbc:h2:mem:wirebarley
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# 기본 설정
server:
  port: 8080

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.yl.wirebarley

# 로깅 설정
logging:
  level:
    org.springdoc: DEBUG
    io.swagger: DEBUG
    com.yl.wirebarley: DEBUG

transaction:
  limit:
    daily:
      withdrawal: 1000000 # 일일 출금 한도 (1,000,000원)
      transfer: 3000000   # 일일 이체 한도 (3,000,000원)
  fee:
    transfer: 0.01 # 이체 수수료 (1%)

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true
