spring:
  datasource:
    url: jdbc:h2:mem:wirebarley
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# 기본 설정
server:
  port: 8080

# 공통 설정
transaction:
  limit:
    daily:
      withdrawal: 1000000 # 일일 출금 한도 (1,000,000원)
      transfer: 3000000   # 일일 이체 한도 (3,000,000원)
  fee:
    transfer: 0.01 # 이체 수수료 (1%)

---
spring:
  config:
    activate:
      on-profile: account
  application:
    name: account-service
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: transaction
  application:
    name: transaction-service
server:
  port: 8082
