spring:
  application:
    name: transaction-service
  profiles:
    include: common
  
server:
  port: 8082

transaction:
  limit:
    daily:
      withdrawal: 1000000
      transfer: 3000000
  fee:
    transfer: 0.01